image: golang:latest

stages:
  - build

building:
  stage: build
  script:
    - go install github.com/pepa65/cprice@latest
    - GOOS=linux GOARCH=amd64 go build -ldflags="-s -w"
    - GOOS=linux GOARCH=arm go build -ldflags="-s -w" -o cprice_pi
    - GOOS=freebsd GOARCH=amd64 go build -ldflags="-s -w" -o cprice_bsd
    - GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o cprice_osx
    - GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o cprice.exe
  artifacts:
    name: cprice
    paths:
     - cprice
     - cprice_pi
     - cprice_bsd
     - cprice_osx
     - cprice.exe
